package site.soulware.cocina360.shared.domain.model.valueobject;

import java.util.UUID;

/** Identity of a {@code Profile}. Mirrors {@code auth.users.id} from Supabase Auth — never generated by this service. */
public final class ProfileId extends AggregateId {

    public ProfileId(UUID value) {
        super(value);
    }

    public static ProfileId of(UUID value) {
        return new ProfileId(value);
    }
}
