spring.application.name=cocina360

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.cxvvqoiqzcnvmnthdour
spring.datasource.password=ug7xMf8SXjgnn51U
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mongodb.uri=mongodb+srv://cocina360-backend-application:hMxocUOmdBJyg3wk@na-west.seurs.mongodb.net/cocina360?appName=NA-WEST
spring.mongodb.representation.uuid=standard
spring.data.mongodb.auto-index-creation=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.jdbc=DEBUG

spring.mvc.locale=en
spring.mvc.locale-resolver=accept-header
server.forward-headers-strategy=framework