spring.application.name=cocina360

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.representation.uuid=standard
spring.data.mongodb.auto-index-creation=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.jdbc=DEBUG

spring.mvc.locale=en
spring.mvc.locale-resolver=accept-header
server.forward-headers-strategy=framework