spring.jpa.show-sql=true
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

app.cors.allowed-origins=http://localhost:3000,http://localhost:4200
app.provisioning.enabled=true
